//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.09.06 at 01:46:23 PM CEST
//

package com.janis.bgg.demo.XMLObjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}item"/>
 *       &lt;/sequence>
 *       &lt;attribute name="termsofuse" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "item"
})
@XmlRootElement(name = "items")
public class Items {

    @XmlElement(required = true)
    protected Item item;
    @XmlAttribute(name = "termsofuse", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String termsofuse;

    /**
     * Gets the value of the item property.
     * 
     * @return
     *         possible object is
     *         {@link Item }
     * 
     */
    public Item getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *            allowed object is
     *            {@link Item }
     * 
     */
    public void setItem(Item value) {
        this.item = value;
    }

    /**
     * Gets the value of the termsofuse property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getTermsofuse() {
        return termsofuse;
    }

    /**
     * Sets the value of the termsofuse property.
     * 
     * @param value
     *            allowed object is
     *            {@link String }
     * 
     */
    public void setTermsofuse(String value) {
        this.termsofuse = value;
    }

}
